import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Providers from "./components/ProgressBarProvider";


const AeonikBold = localFont({
  src: "../assets/fonts/AeonikProBold.otf",
  display: "swap",
  variable: "--font-AeoniK-Bold",
});

const AeonikRegular = localFont({
  src: "../assets/fonts/AeonikProRegular.otf",
  display: "swap",
  variable: "--font-AeoniK-Regular",
});
const AeonikLight = localFont({
  src: "../assets/fonts/AeonikProLight.otf",
  display: "swap",
  variable: "--font-AeoniK-Light",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${AeonikBold.variable} ${AeonikRegular.variable} ${AeonikLight.variable} `}>
        <Providers>
        {children}
        </Providers>
      </body>
    </html>
  );
}
